spring:
  # DB Config
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: deep
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA Config
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Migration
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8050
